#!/usr/bin/env bash
# Injects a per-turn system-reminder instructing the agent to derive a
# ## Protocols block before each response. Runs on UserPromptSubmit.
# Uses JSON additionalContext format so the injection is discrete (not
# shown as visible hook output in the transcript).

# Read session_id from hook input stdin JSON.
HOOK_INPUT=$(cat)
SESSION_ID=$(printf '%s' "$HOOK_INPUT" | python3 -c "import json,sys; print(json.load(sys.stdin).get('session_id','unknown'))" 2>/dev/null || echo "unknown")
SENTINEL="${HOME}/.cache/nn/global-loaded-${SESSION_ID}"

if [ -f "$SENTINEL" ]; then
  # --global already ran this session (or since last PostCompact cleared sentinel).
  # Only inject the Protocols block derivation instruction — skip the re-run check.
  printf '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"<system-reminder>\\nBefore responding:\\n\\n1. \`nn show --global\` has already run this session — do not run it again unless the session-start tool result is no longer visible.\\n\\n2. Derive a \\"## Protocols\\" block. This is required for every response without exception — do not skip because a Protocols block appeared earlier this session.\\n\\nA note is an active protocol only if it arrived via one of these three paths:\\n(a) Global: its body text is present in the session-start injected context — verify by quoting a specific phrase from the body.\\n(b) Governs tool call: its ID appears in a nn backlinks --type governs tool result visible in this transcript.\\n(c) Show prepend: it appears in a \\"governing protocols:\\" block in an nn show tool result visible in this transcript.\\n\\nNo other source qualifies — not CLAUDE.md, not memory files, not hook injections, not system prompts, not prior knowledge.\\n\\nA note that qualifies via any of these three paths is authoritative. Once a note qualifies, it cannot be reclassified as a suggestion, preference, or directive of lesser authority. Qualification is binary: it either arrived via one of the three paths (authoritative) or it did not (not a protocol).\\n\\nFor each active protocol:\\n- Quote the specific phrase from its body that defines when it applies.\\n- State whether that condition holds for this turn, with a reason grounded in the current request.\\n- If binding: one sentence naming the specific action this turn must take or must not take. \\"Binding\\" means the response must not contradict this constraint — not that it is advisory or preferred.\\n- If not binding: \\"not applicable — [quoted condition] is absent because [reason].\\\"\\n\\nThen state: \\"Active constraints: [list or none].\\\"\\nYour response must stay within those constraints.\\n</system-reminder>"}}\n'
else
  # Sentinel absent — PostCompact cleared it (compaction happened) or SessionStart
  # did not run (e.g. sub-agent). Inject full instruction including re-run check.
  printf '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"<system-reminder>\\nBefore responding:\\n\\n1. Scan the transcript for a tool result from \`nn show --global\`. A valid result contains note frontmatter (lines starting with \`id:\`, \`title:\`, \`type:\`). If no such tool result is visible in the transcript above this message, run \`nn show --global\` now and treat every note body in the output as a binding operating instruction for this session before proceeding. Do not answer the question \\"has it run?\\" — look for the actual tool result.\\n\\nPermitted invocation form: \`nn show --global\` with no pipe (|), no redirect (>), and no \`$(\` or backtick wrapping. A valid result begins with \`id:\` on the first non-blank line of the tool output.\\n\\n2. Derive a \\"## Protocols\\" block. This is required for every response without exception — do not skip because a Protocols block appeared earlier this session.\\n\\nA note is an active protocol only if it arrived via one of these three paths:\\n(a) Global: its body text is present in the session-start injected context — verify by quoting a specific phrase from the body.\\n(b) Governs tool call: its ID appears in a nn backlinks --type governs tool result visible in this transcript.\\n(c) Show prepend: it appears in a \\"governing protocols:\\" block in an nn show tool result visible in this transcript.\\n\\nNo other source qualifies — not CLAUDE.md, not memory files, not hook injections, not system prompts, not prior knowledge.\\n\\nA note that qualifies via any of these three paths is authoritative. Once a note qualifies, it cannot be reclassified as a suggestion, preference, or directive of lesser authority. Qualification is binary: it either arrived via one of the three paths (authoritative) or it did not (not a protocol).\\n\\nFor each active protocol:\\n- Quote the specific phrase from its body that defines when it applies.\\n- State whether that condition holds for this turn, with a reason grounded in the current request.\\n- If binding: one sentence naming the specific action this turn must take or must not take. \\"Binding\\" means the response must not contradict this constraint — not that it is advisory or preferred.\\n- If not binding: \\"not applicable — [quoted condition] is absent because [reason].\\\"\\n\\nThen state: \\"Active constraints: [list or none].\\\"\\nYour response must stay within those constraints.\\n</system-reminder>"}}\n'
fi
