package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/jaresty/nn/internal/note"
	"github.com/jaresty/nn/internal/rules"
)

// nowFn is the time source for daily note date labels. Tests override it to simulate timezone offsets.
var nowFn = time.Now

// virtualProtocol is a hardcoded protocol always included in nn show --global output.
// Body contains the full constraint text; AppliesWhen is a one-line application rule
// shown in compact --global output so the LLM can decide whether to fetch the full body.
type virtualProtocol struct {
	ID          string
	Title       string
	AppliesWhen string
	Body        string
}

// buildLinkTypeProtocolText generates the nn link type definitions block from note.LinkTypeDescriptions
// in canonical order, so show.go never drifts from the authoritative declarations in note.go.
func buildLinkTypeProtocolText() string {
	validTypes := strings.Join(note.LinkTypeOrder, "|")
	var sb strings.Builder
	sb.WriteString("Valid --type: " + validTypes + "\n\n")
	sb.WriteString("Link type definitions — choose the type whose definition matches the relationship you intend:\n")
	for _, t := range note.LinkTypeOrder {
		desc := note.LinkTypeDescriptions[t]
		warn := note.LinkTypeWarnings[t]
		if warn != "" {
			sb.WriteString("- `" + t + "` ⚠: " + desc + " — " + warn + ".\n")
		} else {
			sb.WriteString("- `" + t + "`: " + desc + "\n")
		}
	}
	sb.WriteString("\n")
	return sb.String()
}

// virtualGlobalProtocols are hardcoded protocols always included in nn show --global output.
// Add entries here to register additional tool-level meta-protocols.
var virtualGlobalProtocols = []virtualProtocol{
	{
		ID:          "virtual-nn-capture-discipline",
		Title:       "Protocol: nn-capture-discipline",
		AppliesWhen: "before any Read tool call, or any Bash call that reads a file from disk or queries an external service (network, API, database)",
		Body: "**Anti-skip-resistance rule:** Any assistant text that cites prior knowledge, familiarity, or certainty about a topic as a reason not to run the gate search is itself a gate violation — prior knowledge is the condition under which the search is *most* likely to return a relevant note, not a reason to skip it. An evaluator detects this violation by finding phrases such as \"I already know,\" \"I'm familiar with,\" \"no need to search,\" or \"I know where this is\" in assistant text immediately before a gated action that has no `Gate:` line.\n\n" +
			"Before any Read tool call, or any Bash call that reads a file from disk or queries an external service (network, API, database), " +
			"and not on the allow-list, the last " +
			"line of your assistant text before that call must begin with `Gate:` followed by either:\n" +
			"- `Gate: allow-listed — [item]` for allow-listed actions\n" +
			"- `Gate: Search rationale: [topic] — [action]` otherwise\n\n" +
			"Then run `nn list --search \"<topic>\" --json --fields id,title,score,match_reason` as the complete Bash tool call text — " +
			"no additional flags, arguments, or shell operators. " +
			"The tool result must appear in the transcript. " +
			"The assistant text immediately following that result must do one of:\n\n" +
			"**(a) Found path:** If the result array is non-empty, quote the title of the top result (index 0), " +
			"then write one sentence beginning " +
			"`Selected because:` that cites both the `score` value and the `match_reason` value verbatim from that result's JSON object. " +
			"Then run `nn show <id>` on that result before the gated action. " +
			"The `nn show` tool result must appear in the transcript before the gated action proceeds. " +
			"`nn show` calls within the search window do not reset it. Otherwise, treat the result as empty and follow the **Empty/truncated path**.\n\n" +
			"**(b) Empty/truncated path:** Write `skip-search: <quoted substring>` where `<quoted substring>` " +
			"is a string that appears verbatim in the tool result (e.g. `[]`, a count string, or a truncation marker). " +
			"This is the only permitted exit without a `Selected because:` line — " +
			"any other form of declaring no results is a gate violation.\n\n" +
			"**Repeat search suppression:** If a search whose `--search \"<q>\"` argument string matches a prior call's `--search \"<q>\"` argument string " +
			"already produced a `skip-search:` or `not relevant:` exit in this session, " +
			"write `skip-search: already searched this session — \"<q>\"` " +
			"(where `\"<q>\"` is the literal `--search` argument string) and proceed.\n\n" +
			"**Allow-list (no gate required):**\n" +
			"- Any Bash call that invokes a CLI tool to retrieve that tool's own output — the tool is authoritative for its own domain (e.g. `bar lookup`, `go doc`, `git log`); no nn gate is needed before such calls\n" +
			"- Any file written or generated by this session (Write, Edit, or session command output)\n" +
			"- Any command producing output solely from session state (tests, builds, linters)\n" +
			"- Live machine-generated output (JSON, log, status) where a resource identifier for that " +
			"system appears in the conversation above this action\n" +
			"- `nn read <file>` — use this instead of a bare Read or cat call; writing `Gate:` before `nn read` is a protocol violation (the call itself satisfies the gate)\n" +
			"- `nn grep <pattern> [path]` — use this instead of a bare grep or find+read to search code; the call itself satisfies the gate\n" +
			"- `nn trace <root-dir> --symbol <name> [--root <dir>]` or `nn trace <file>:<line>` — use this instead of grep when tracing call graphs or symbol relationships across files; add `--root <dir>` to index a wider directory (e.g. the repo root) so cross-package calls resolve; the call itself satisfies the gate\n" +
			"- `nn ast <file>` — print structural outline of a source file; the call itself satisfies the gate\n" +
			"- `nn ast <file> --refs` — also search for name-match references across --root; the call itself satisfies the gate\n" +
			"- `nn tee` — pipe stdin through unchanged while printing BM25-matched related notes to stderr; the call itself satisfies the gate\n" +
			"- `nn shuf [<path>...]` — sample random units from files or directories (recurses) (or stdin) and show BM25-matched notes; the call itself satisfies the gate\n\n" +
			"After the gated action, quote a verbatim excerpt from the result (minimum: one complete clause or value).\n\n" +
			"**If `skip-search:` appeared above this action:** before capturing, apply the durable-claim test: ask — *is this finding a durable, non-derivable claim about the codebase or domain?* A finding is durable if it would not be invalidated by routine code changes; it is non-derivable if a future reader could not recover it by running `find`, `grep`, or reading source files. If the finding fails either condition — e.g. a file's location, a symbol's name, a config value, a lookup answer — write `ephemeral: skip` and stop; do not capture. If the finding passes, run `nn new --quick --title \"<finding>\"` where `<finding>` is the excerpt restated as a claim.\n\n" +
			"**If `Selected because:` appeared above this action:** the gate found a relevant note. Quote a sentence from the `nn show` result — the sentence must appear verbatim in the preceding `nn show` tool-result block. Then write: `compare: note sentence = \"<verbatim sentence from nn show>\" / finding = \"<claim>\" — [same topic | different topic] / [present | absent] / [durable | ephemeral]`. Then:\n" +
			"- If the compare: line shows `different topic`: write `not relevant: <one-sentence reason>` — `not relevant:` is the terminal write in this gate window — no `nn update` tool call follows.\n" +
			"- If the compare: line shows `ephemeral`: the finding describes a transient state that the current session's work will invalidate — write `ephemeral: skip` and stop; do not append to the subject note.\n" +
			"- If the finding adds a claim absent from that sentence: write `not in note: <claim>`, then run `nn update <id> --append \"<claim>\" --since <modified>` using the `<id>` and `modified:` value from the `nn show` result.\n" +
			"- If the finding is already represented: write `represented by: <quoted note title>` — no action needed.\n\n" +
			"**Staleness check (runs after any `nn show` in the gate window, independent of compare outcome):** Expiry keys on *claim volatility*, not concreteness — the question is: could a future change make this note's asserted claim false or unsafe to rely on? Concreteness is a poor proxy: a source- and date-bounded fact is concrete yet permanently true. After reading the note body, classify its central claim into exactly one of three categories and write the matching `stale:` line:\n" +
				"- **Historical observation** — the claim is explicitly bounded to a past source, event, commit, or version (e.g. \"the March 4 RFP stated X\", \"commit abc123 implemented Y\"). It stays true because it is anchored to that source/time. Write `stale: historical — bounded to past source, retain` and take no expiry action, regardless of age.\n" +
				"- **Current-state claim** — the claim's truth depends on mutable present or future conditions (e.g. \"production currently uses X\", \"main points to Y\", \"this workaround is required\"). A later change can invalidate it. Check `modified:`: if modified >14 days ago, write `stale: current-state — mutable, flagging` and run `nn update <id> --expires <date+14d> --since <modified>` (where `<date+14d>` is today plus 14 days, YYYY-MM-DD); if modified >28 days ago use `<date+7d>` instead. If recently modified, write `stale: current-state — recent` and take no action yet.\n" +
				"- **Forecast or unresolved assumption** — the claim predicts or presumes without confirmation (e.g. \"the team plans to launch X\", \"this is probably the authoritative workflow\"). Prefer a condition over a date: write `stale: forecast — set expires-when` and run `nn update <id> --expires-when \"<condition under which the claim should be revalidated>\" --since <modified>` (e.g. \"stakeholders confirm authority\").\n" +
				"Decision sequence: is the claim explicitly bounded to a past source/event/version? If yes → historical, retain. If no → does its truth depend on mutable present or future conditions? If yes → current-state (expiry) or forecast (expires_when); if no (a timeless principle or model) → write `stale: timeless — retain` and take no action.\n\n" +
			"**If the quoted result is an existing draft note:** promote it — `nn update <id> --status reviewed` — re-discovery is the usefulness signal.\n",
	},
	{
		ID:          "virtual-nn-cli-reference",
		Title:       "Protocol: nn CLI reference",
		AppliesWhen: "always — reference for valid nn command flags, types, and statuses",
		Body: "**nn new** `--title \"...\" --type <type> --content \"...\" --no-edit [--tags \"t1,t2\"] [--link-to <id> --annotation \"...\"] [--applies-when \"...\"] [--representation <rep>] [--expires YYYY-MM-DD] [--expires-when \"condition\"] [--check]`\n" +
			"Valid --type: concept|argument|model|hypothesis|observation|question|protocol\n" +
			"New notes are always created as draft. Promote with: `nn update <id> --status reviewed`\n" +
			"**nn new --quick** `--title \"...\" --no-edit` — quick capture: sets type=observation, status=draft, content empty; no --type required\n" +
			"**nn new --no-suggest** — skip link/tag suggestion prompt after creation; use in non-interactive or batch contexts\n" +
			"Note: `--content` is literal — the shell does not expand `\\n` in double-quoted strings. Use `$'...'` ANSI-C quoting or pipe via stdin for multiline content.\n" +
			"Note: `--link-to` and `--annotation` are repeatable and must be paired (one `--annotation` per `--link-to`).\n\n" +
			"**nn update** `<id> --since <RFC3339> --status <status>` | `--title \"...\"` | `--applies-when \"...\"` | `--expires YYYY-MM-DD` | `--expires-when \"condition\"` | `--clear-expires` | `--clear-expires-when` | `--content \"...\" --no-edit` | `[--link-to <id> --annotation \"...\"] [--check]`\n" +
			"Valid --status: draft|reviewed|permanent\n" +
			"--since is required: read 'modified:' from nn show output; update is rejected if the note was changed after that timestamp\n" +
			"--clear-expires removes the expiration date; --clear-expires-when removes the expires_when condition.\n" +
			"--link-to and --annotation are repeatable and must be paired; --check runs representation graph validation after update (no-op if note has no representation).\n\n" +
			"**nn promote** `<id> --to <status>` — advance note status (draft→reviewed→permanent); reads note before writing and errors on concurrent modification conflict rather than overwriting\n\n" +
			"**nn delete** `<id> [--confirm]` — delete a note (warns if linked-to by others); `--from-stdin` reads IDs line-by-line from stdin\n\n" +
			"**nn todo list** `[--all] [--waiting] [--context <name>]` — list open checkboxes grouped by note (ID + title header, `- [ ]` lines beneath); default excludes notes blocked by an incomplete `requires` target and excludes items tagged `[waiting: reason]`; `--all` shows all notes with open items regardless; `--waiting` shows only items tagged `[waiting: reason]` (surfaces the reason); `--context <name>` filters to items tagged `@<name>`; notes tagged `daily` created before today are always excluded (historical daily notes carry todos forward to the current day)\n" +
			"**nn todo done** `<id> <pattern> [<pattern>...] [--resolution \"why\"]` — mark matching `- [ ]` checkbox(es) as done (`- [x]`) in a single write. Matching: if a single open checkbox line contains every <pattern>, that one line is flipped (conjunctive AND — narrow one item with multiple patterns); otherwise each <pattern> flips its own distinct open line (batch — flip several items at once, avoiding parallel `nn todo done` calls that race and fail the concurrency check). All-or-nothing — if any pattern matches no open checkbox the note is left unchanged; `--resolution` appends commentary explaining why to each flipped line\n" +
			"**nn todo reopen** `<id> <pattern> [<pattern>...]` — mark matching `- [x]` checkbox(es) as not done (`- [ ]`) in a single write; same conjunctive-single-line-else-distinct-line matching as `nn todo done`; all-or-nothing — if any pattern matches no done checkbox the note is left unchanged\n" +
			"**nn todo set** `<id> <pattern> [--waiting reason] [--clear-waiting] [--context name] [--clear-context]` — add/replace or remove inline metadata tags on a matching open checkbox line; `--waiting reason` adds/replaces `[waiting: reason]`; `--clear-waiting` removes it; `--context name` adds/replaces `@name`; `--clear-context` removes it\n" +
			"Todo items in notes must be written as `- [ ]` (open) or `- [x]` (done) so they are discoverable via `nn list --has-open-items`, listed via `nn todo list`, and manageable via `nn todo done`/`nn todo reopen`.\n" +
			"Inline todo metadata (on the same `- [ ]` line): `[waiting: reason]` marks an item as waiting on something external (hidden by default, shown with `--waiting`); `@context` tags an item with a GTD-style context (filterable with `--context <name>`).\n\n" +
			"**nn remind** `\"content\" [--for N] [--expires YYYY-MM-DD]` — creates observation tagged 'reminder', permanent, expires today+1d by default; surfaces in nn show --global\n" +
			"**nn remind --find FRAGMENT** — search reminder titles by substring; prints matching ID; error if ambiguous (multiple matches) or zero matches\n" +
			"**nn remind \"new body\" --update ID** — replace body of existing reminder in place; preserves expiry; no new note created\n\n" +
			"**nn check** `<id> [--as <representation>] [--set-representation]` — validate the graph structure of a representation subgraph rooted at a note; traverses only same-representation outgoing links; reports all violations\n" +
			"Graph checks (all representations): root must be type:model; non-root nodes must be type:concept or type:argument; cycles fail\n" +
			"Representation-specific: ontology = connectivity only; taxonomy = all links must be refines or extends; axiom = root must have ≥1 grounded-by link\n" +
			"Does NOT check section headers within note bodies — use semantic review for body structure\n\n" +
			"**nn rules check** — evaluate Datalog rules over all notes and print every `violation(ID, Reason)`; exits non-zero if any exist. Rules come from built-in invariants plus any ` ```nn-rule ` fenced blocks in note bodies.\n" +
			"**nn rules query** `<predicate>` — print all derived facts for a predicate (e.g. `nn rules query violation`); use to inspect derivation output.\n" +
			"**nn rules list** — list rules loaded from note bodies with note-ID provenance, plus the built-in rule count and the names of all built-in queryable predicates.\n" +
			"Auto-exposed facts (closed-world, from every note): `note(ID, Type, Status)`, `link(From, To, LinkType)`, `tag(ID, Tag)`, `open_item(ID, Text)`, `expires(ID, YYYY-MM-DD)`, `representation(ID, Rep)`.\n" +
			"Built-in queryable derived predicates (via `nn rules query <pred>`; run `nn rules list` for the full set): `reachable(A, B)` — B reachable from A via any links; `transitively_governs(P, N)` — protocol P governs N down refines/extends chains; `done(X)` — X has no open checkbox items (satisfied task); `blocked(X)` — X has a `requires` link to a not-done or itself-blocked target (transitive task dependency); `violation(ID, Reason)` — structural check failures.\n" +
			"Rule syntax lives in a ` ```nn-rule ` fenced block in a note body: `head(X) :- body1(X), !body2(X).` — `_` is a wildcard, uppercase args are variables, quoted/lowercase are constants, `!` negates. A malformed rule warns (with note ID) and is skipped; it never breaks note loading.\n\n" +
			"**nn list** `--search \"<q>\" --show-first --json [--fields id,title,...]` | `--type <type>` | `--status <status>` | `--representation <rep>` | `--orphan` | `--since <ISO>` | `--before <ISO>` | `--expired` | `--has-expires` | `--has-open-items` | `--unblocked`\n" +
			"Output shaping (require --json): `--rich` (adds modified/link_count/body_preview) | `--full` (disables excerpt/annotation truncation) | `--envelope` (wraps in metadata envelope with query/result_count/total_matching; requires --search)\n" +
			"Search ranking: `--boost-recent` boosts recently-modified notes (requires --search)\n" +
			"Valid --fields: id|title|type|status|tags|applies_when|excerpt|score|modified|match_reason|is_protocol|link_count|backlink_count|created|body_preview|representation (requires --json; errors on unknown field)\n" +
			"`nn list --search` always includes 1-hop graph neighbors in output: plain text shows indented `→`/`←` lines (id, title, type, annotation); `--json` includes a `neighbors` array with direction/id/title/type/annotation fields.\n\n" +
			"**Search-to-graph routing.** Use `nn list --search` to locate an anchor note. Do not stop at ranked search results when the request concerns relationships, synthesis, support, change impact, disagreement, dependencies, or context — search identifies *relevance*, graph traversal identifies *structure*. Do not treat BM25 similarity as evidence of a relationship. After selecting an anchor, inspect its graph when the request asks: what supports/grounds/extends/refines/contradicts a claim; what a meeting/artifact/finding changes; the risks, implications, dependencies, or surrounding context; how two notes/decisions/topics relate; a summary spanning multiple evidence types; whether a conclusion is isolated or corroborated; or uses trigger words like \"why\", \"biggest risks\", \"what changed\", \"what supports/depends on this\", \"related\", \"context\", \"neighborhood\", \"how does X connect to Y\", \"what else do we know\", \"summarize the evidence\".\n" +
			"Workflow: `search → select anchor → nn graph show --focus <id> --depth 1 --direction both --zones → inspect key note bodies → answer`. When a neighbor shows an unusually high degree (`↑out ↓in` markers), treat it as a likely hub worth visiting even if off the direct question — high inbound degree signals a load-bearing note. For iterative positioned exploration — walking the graph hop-by-hop rather than answering from one neighborhood — use the Navigation mode workflow (enter → orient → read → recenter → arrive) in the nn-guide skill, built on `nn graph show --zones --bodies --color always`. To jump into the graph from cold — no current focus — teleport: search-to-cluster (surface landing zones via `nn clusters` / high-degree hubs, not a ranked hit list) or random (`nn random`); see the nn-guide for scan (see wide) and peek (look without moving).\n" +
			"Default neighborhood: `nn graph show --focus <id> --depth 1 --direction both --zones --format text` — `--zones` groups the anchor's direct neighbors under TOP (what it answers to), BOTTOM (what builds on it), LEFT (tension: contradicts/questions), RIGHT (lateral: source-of/requires), which maps onto the routing trigger questions. Use `--depth 1` with `--zones`: only direct neighbors carry a zone, and the zoned text view omits unzoned nodes — so for the full 2-hop neighborhood use `--depth 2` *without* `--zones`. Then narrower helpers as needed: incoming influence/use → `nn backlinks <id>`; outgoing endorsed claims/evidence → `nn links <id>`; connected note bodies → `nn show <id> --depth 2`; relationship between two anchors → `nn path <a> <b>`; topic-level structure/hubs → `nn clusters`; notes that connect otherwise-disconnected parts of the graph (integration points / load-bearing links between topic areas) → `nn graph bridges`, or query-conditioned Scan → `nn graph bridges --search \"<query>\" --format json`; potentially missing edges → `nn list --similar <id>`. Use `--direction outgoing` for what grounds or follows from the anchor, `--direction incoming` for who relies on/extends/operationalizes it, `both` when exploratory.\n\n" +
			"**nn show** `<id>` | `--global` | `[--rules]`\n" +
			"`nn show` output must not be piped to `head`, `tail`, `less`, or `more`. Pipe the full output or omit the pipe — the complete note body is required for accurate retrieval.\n" +
			"Output format: Links and Backlinks sections each render as `[[id|title]] [type] {status} — annotation` (fields omitted when empty).\n" +
			"`--rules` appends a `## Rule violations` section for the shown note (runs the rules engine over the notebook); omitted by default for speed. Use `nn rules check` for a full-notebook sweep.\n\n" +
			"**nn link** `<from> <to> --type <type> --annotation \"...\"`\n" +
			buildLinkTypeProtocolText() +
			"**nn unlink** `<from> <to> [--type <type>]` — remove a link between two notes; accepts id or title substring for both arguments; `--type` removes only edges of that type, otherwise all edges between the pair are removed\n\n" +
			"**nn read** `<file> [--lines N-M[,N-M,...]] [--limit N]` — read file with line numbers; appends `## Related notes` from BM25 search on shown content\n\n" +
			"**nn grep** `<pattern> [path] [-i|--ignore-case] [--context N] [--notes-per-match K] [--max-matches N] [--trace] [--context-report]` — search files for pattern and annotate each match with related nn notes via BM25 on surrounding context; use instead of bare grep when working in a codebase to surface relevant knowledge alongside code locations; `-i`/`--ignore-case` makes matching case-insensitive; `--trace` invokes nn trace inline for each traceable matched file; `--context-report` appends retained source-window counts and exact gross, unique, and overlap line totals\n\n" +
			"**nn trace** `<root-dir> --symbol <name> [--symbol <name> ...] [--depth N] [--json] [--show-unresolved] [--root <dir>]` or `<file>:<line>` — syntax-aware call graph from entry-point symbols using gotreesitter; prefer over nn grep when tracing how a symbol is called or what it calls across files; annotates each resolved node with related nn notes via BM25; emits human-readable tree by default or JSON graph with --json; `file:line` form resolves the symbol at that line automatically; `--root <dir>` widens the index scope (language-agnostic) so calls to definitions in sibling packages resolve instead of showing as unresolved — pass the repo/project root to follow logic across packages\n\n" +
			"**nn ast** `<file> [--json] [--refs] [--root <dir>]` — print compact structural outline of a source file (functions, types, imports); `--refs` additionally searches for name-match references across `--root`; text output always appends `## Related notes` via BM25; `--json` emits symbol array only\n\n" +
			"**nn tee** — reads stdin, writes it unchanged to stdout, and prints BM25-matched related notes to stderr; use in pipelines where stdout must stay clean (e.g. `curl <url> | nn tee | jq .`)\n\n" +
				"**nn fetch** `<url> [--capture]` — HTTP GET a URL, strip HTML to plaintext, print to stdout with `## Related notes` from notebook via BM25. `--capture` creates a draft observation note with the fetched body.\n\n" +
				"**nn search-web** `<query> [--results N]` — best-effort web search via DuckDuckGo; fetches top N result URLs (default 3), strips HTML, prints `## Result N:` header + 500-char preview + `## Related notes` from notebook per result.\n\n" +
			"**nn shuf** `[<path>...] [--count N] [--unit lines|paragraphs|symbols]` — sample N random units from files or directories (recurses into dirs) (or stdin) and print BM25-matched notes beneath each sample; use when you want statistical coverage of a corpus rather than targeted search — the inverse of grep. `--unit symbols` uses treesitter to sample whole functions/types (falls back to paragraphs for unsupported languages). Binary files are skipped with an aggregate stderr count. Sample units larger than 65536 bytes are also skipped and counted. Piped stdin is not MIME-filtered but uses the same unit-size limit. Use `nn shuf` over: `nn grep` when you have no specific query and want serendipitous note matches; `nn tee` when you want to sample rather than consume all input; `nn random` when the corpus is files, not notes.\n\n" +
			"**nn show** `<id> --depth N` — traverse N hops of outgoing links from a note\n\n" +
			"**nn path** `<id-a> <id-b> [--links TYPE,...] [--json]` — shortest undirected path by default; `--links` returns a directed typed witness, with ordered nodes and edges in JSON for Navigation Recenter\n\n" +
			"**nn clusters** — topological clusters via label propagation\n\n" +
			"**nn random** `[--tag TEXT] [--type TYPE] [--status STATUS] [--json] [--depth N] [--max-backlinks N]` — return a randomly selected note; `--depth N` traverses outgoing links up to N hops; `--max-backlinks N` filters to notes with at most N inbound links (surface underlinked notes for integration review)\n\n" +
			"**nn list** `--similar <id>` — BM25 similarity (notes sharing vocabulary but not linked)\n\n" +
			"**nn graph** `[--json]` — export full graph as JSON `{ \"nodes\": [...], \"edges\": [...] }`\n\n" +
			"**nn graph show** `[--focus <id>] [--depth N] [--direction outgoing|incoming|both] [--links TYPE,...] [--status STATUS,...] [--representation VALUE] [--zones] [--bodies] [--color auto|always|never] [--format text|json|mermaid]` — traversal-filtered graph output (LLM-facing; focused traversal defaults to depth 2 and direction outgoing); link, status, and representation filters constrain BFS expansion rather than hiding nodes after traversal; Mermaid preserves stored edge orientation and emits deterministic provenance comments. Without --focus, graph show renders the full graph; explicitly supplied traversal flags require `--focus`. `--zones` (requires `--focus`) annotates each node with the directional screen zone it occupies relative to the focus, derived from its direct link to the focus: TOP = what the focus answers to (governs/supports incoming, or refines/extends/grounded-by outgoing from focus); BOTTOM = what builds on the focus (governs/supports outgoing, or refines/extends/grounded-by incoming); LEFT = tension (contradicts, questions); RIGHT = lateral provenance/task edges (source-of, requires). In `--format json` each node gains a `zone` field (omitted when empty); in `--format text` nodes are grouped under TOP/LEFT/RIGHT/BOTTOM headers, preceded by a zone→link-type key. This is the same zone mapping the interactive HTML viewer uses. Every node carries a link-degree marker: `--format text` appends `↑<out> ↓<in>` to each node line; `--format json` adds `out_degree`/`in_degree` fields (degree is over the whole notebook, so it distinguishes a hub from a leaf). `--color auto|always|never` (default auto) prefixes text output with colored-circle emoji markers (chosen over ANSI so they survive markdown/relay): zone headers by zone, node titles by note type, edge labels by link family (🔴 tension/🔵 lateral/🟦 structural) — auto emits markers only to a TTY (piped output and json stay clean), always forces them (use when relaying to a human), never suppresses them. `--bodies` includes each node's full body inline (and its tags in `--format text`) so a zoned view can be *read* as well as navigated — one call replaces the search→zone→per-node `nn show` loop; in `--format json` each node gains a `body` field (omitted when empty). Combine `--zones --bodies` for a self-contained \"navigator with contents\": neighbors bucketed by zone, each printed with its tags and body.\n\n" +
			"**nn graph apply** `<manifest.yaml> (--dry-run | --commit)` — create notes and edges atomically from a YAML changeset manifest (one of --dry-run or --commit is required; --dry-run prints the plan without writing, --commit writes all notes and edges in one commit). Manifest schema:\n" +
			"  `notes:` list — each item: `title` (required), `type` (required, valid --type), `key` (optional local ref for edges; must be unique), `content` (optional body), `tags` (optional list), `applies_when` (optional). New notes are created as draft.\n" +
			"  `edges:` list — each item: `from`, `to` (each a manifest `key` OR `existing:<note-id>`), `type` (link type), `annotation` (required — errors if missing).\n\n" +
			"**nn ask** `[--surface canvas|document|web] [--instructions \"...\"] [--mermaid \"<diagram>\"] [--document <file|folder|url>]` — ask a human for feedback via a chosen surface; blocks until they submit, then prints the result path. The result is a thin envelope at `<session-dir>/result.json` naming native artifacts (path-referenced); the agent reads the artifact and decides what, if anything, becomes a note — nothing is filed automatically. Runs without a configured notebook. Session directories are ephemeral: each run reclaims sessions older than 7 days.\n" +
			"  `--surface canvas` (default) — hosted Excalidraw diagram editor; `--mermaid` seeds it with an editable diagram; writes `result.excalidraw` + `result.png`.\n" +
			"  `--surface document` — delegated to the `plannotator` peer for text/markdown annotation; annotates `--document <file|folder|url>` when given (plannotator fetches a URL itself), else the `--instructions` text; writes `result.plannotator.json` (a `{decision, feedback}` object the agent reads).\n" +
			"  **MCP/skill surface (async, LLM-driven)** — for surfaces reached via an arbitrary MCP server or skill (e.g. a wireframe MCP), nn does NOT drive the surface; the LLM does. Unlike canvas/document/graph (nn hosts or delegates and blocks until submit), this is a handshake the LLM runs: (1) invoke the MCP tool or skill, populate it with the question + context, and — if it returns a URL or openable artifact — open it for the human (e.g. `open <url>`) rather than making them open it themselves; (2) wait for the human to finish in that surface; (3) read back the surface's contents via the same MCP/skill — this requires the surface to expose a read-back operation, not just open/write; if it has no read-back (e.g. a fire-only surface whose state is not fetchable), fall back to a human-couriered result: ask the human to paste the updated link or describe their edits; (4) decide via the thin-envelope discipline what, if anything, becomes a note. Same agent throughout — no nn session, no result.json, no --surface flag; nn's role is only this convention. Use when the human answers on their own clock through a tool the LLM (not nn) can call.\n\n" +
			"For the full command reference, invoke `/nn-guide`.\n",
	},
	{
		ID:          "virtual-nn-error-handling",
		Title:       "Protocol: search nn before workarounding an unexpected command failure",
		AppliesWhen: "when a Bash command, CLI tool, or test fails",
		Body: "When a command fails, run `nn list --search \"<topic>\" --json` before attempting a workaround or fix. " +
			"Prior sessions may have captured the root cause, a known workaround, or a relevant constraint. " +
			"Acting without searching risks repeating a diagnosed problem.\n\n" +
			"**Skip condition A — pre-declared:** if the immediately preceding assistant turn contains a line beginning " +
			"`Expected FAIL: <reason>` (case-insensitive), the lookup is not required. " +
			"Write: `Skipping lookup: cited \"Expected FAIL: <reason>\"` quoting the declaration verbatim.\n\n" +
			"**Skip condition B — self-evident:** if the error output contains a substring that names the cause without ambiguity " +
			"— such as \"No such file\", \"command not found\", \"unrecognized token\", or \"exit status 1\" from a grep/find/cat invocation — " +
			"the lookup is not required. " +
			"Write: `Skipping lookup: self-evident — \"<quoted error substring>\"` quoting the exact substring from the tool output verbatim. " +
			"Absence of either skip declaration means the lookup is required.\n",
	},
	{
		ID:          "virtual-nn-skills",
		Title:       "Protocol: load nn skills via nn skills list",
		AppliesWhen: "at session start, and before any nn workflow operation",
		Body: "If you have not yet run `nn skills list` this session, run it before any `nn skills get` " +
			"or nn workflow operation — its output tells you which skill to load and when:\n\n" +
			"```bash\n" +
			"nn skills list\n" +
			"```\n\n" +
			"Then load the matching skill before responding:\n\n" +
			"```bash\n" +
			"nn skills get <name>\n" +
			"```\n",
	},
}

// protocolDerivationBlock is appended to every protocol note in plain-text display.
// It instructs any LLM reading the note to derive how the protocol applies before responding.
const protocolDerivationBlock = `
<!-- nn:display-only — the following block is injected by nn show and is NOT part of the note body. Do not include it in nn update --content or any note edit. -->

## Protocols

For each protocol listed above:
1. Evaluate its applies_when condition against the current request.
2. If it holds: run ` + "`nn show <id>`" + ` to load the full body, then treat it as a binding constraint.
3. If a protocol has no applies_when field: add an applies_when value via ` + "`nn update <id> --field applies_when --value \"...\"`" + ` before proceeding.

Before responding to any message this session, output a ` + "`## Protocols`" + ` block.
For each active protocol, write one sentence stating how it applies to this specific
request — or "not applicable" if it doesn't. Place this block before your substantive
response.
`

func newShowCmd(state *rootState) *cobra.Command {
	var linkedFrom string
	var jsonOut bool
	var depth int
	var global bool
	var showRules bool

	cmd := &cobra.Command{
		Use:   "show <id-or-title> [<id-or-title>...]",
		Short: "Print note content to stdout (accepts ID or title substring; --depth N for graph traversal)",
		Args:  cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			w := outWriter(cmd)

			if global {
				appendAccessLog(resolveCfgDir(), "--global")
				all, err := state.backend.List()
				if err != nil {
					return fmt.Errorf("show --global: %w", err)
				}
				first := true
				for _, vp := range virtualGlobalProtocols {
					if !first {
						fmt.Fprintln(w, "---")
					}
					first = false
					fmt.Fprintf(w, "id: %s\ntitle: %s\ntype: protocol\nstatus: permanent\napplies_when: %s\n---\n\n%s", vp.ID, vp.Title, vp.AppliesWhen, vp.Body)
				}
				for _, n := range all {
					if n.Type != note.TypeProtocol {
						continue
					}
					hasGoverns := false
					for _, lnk := range n.Links {
						if lnk.Type == "governs" {
							hasGoverns = true
							break
						}
					}
					if hasGoverns {
						continue
					}
					if !first {
						fmt.Fprintln(w, "---")
					}
					first = false
					fmt.Fprintf(w, "id: %s\ntitle: %s\n", n.ID, n.Title)
					if n.AppliesWhen != "" {
						fmt.Fprintf(w, "applies_when: %s\n", n.AppliesWhen)
					}
				}
				now := time.Now().UTC()
				var activeReminders []*note.Note
				for _, n := range all {
					hasReminder := false
					for _, tag := range n.Tags {
						if tag == "reminder" {
							hasReminder = true
							break
						}
					}
					if hasReminder && (n.Expires == nil || !n.Expires.Before(now)) {
						activeReminders = append(activeReminders, n)
					}
				}
				if len(activeReminders) > 0 {
					fmt.Fprintln(w, "---")
					fmt.Fprintln(w, "## Reminders")
					fmt.Fprintln(w)
					for _, n := range activeReminders {
						fmt.Fprintf(w, "### %s\n\n", n.Title)
						if n.Expires != nil {
							fmt.Fprintf(w, "expires: %s\n", n.Expires.Format("2006-01-02"))
						}
						if n.ExpiresWhen != "" {
							fmt.Fprintf(w, "expires_when: %s\n", n.ExpiresWhen)
						}
						fmt.Fprintf(w, "\n%s\n\n", n.Body)
					}
				}
				byIDForTodo := make(map[string]*note.Note, len(all))
				for _, a := range all {
					byIDForTodo[a.ID] = a
				}
				if todosText := listTodosText(all, byIDForTodo); todosText != "" {
					fmt.Fprintln(w, "---")
					fmt.Fprintln(w, "## Todos")
					fmt.Fprintln(w)
					fmt.Fprint(w, todosText)
				}
				if dn, dnErr := resolveDailyNote(state); dnErr == nil {
					fmt.Fprintln(w, "---")
					byID := make(map[string]*note.Note, len(all))
					for _, a := range all {
						byID[a.ID] = a
					}
					backlinkers := findBacklinkers(dn.ID, all)
					if data, merr := dn.Marshal(); merr == nil {
						rendered := renderWithResolvedLinks(string(data), dn, byID, backlinkers, showRules)
						fmt.Fprint(w, rendered)
					} else {
						fmt.Fprintf(w, "id: %s\ntitle: %s\ntype: observation\nstatus: %s\ntags: daily\n---\n\n%s\n", dn.ID, dn.Title, dn.Status, dn.Body)
					}
					if !strings.Contains(dn.Body, "## Relay") {
						fmt.Fprintln(w, "Warning: relay block missing or not updated — check daily note before proceeding.")
					}
				}

				fmt.Fprint(w, protocolDerivationBlock)
				return nil
			}

			if depth > 0 {
				if len(args) != 1 {
					return fmt.Errorf("show --depth: provide exactly one ID")
				}
				root, err := resolveNote(state, args[0])
				if err != nil {
					return fmt.Errorf("show --depth: %w", err)
				}
				all, err := state.backend.List()
				if err != nil {
					return fmt.Errorf("show --depth: list: %w", err)
				}
				byID := make(map[string]*note.Note, len(all))
				for _, n := range all {
					byID[n.ID] = n
				}
				entries := bfsDepth(root, byID, depth)
				if jsonOut {
					return printDepthJSON(w, entries)
				}
				return printDepthMarkdown(w, entries)
			}

			if linkedFrom != "" {
				src, err := resolveNote(state, linkedFrom)
				if err != nil {
					return fmt.Errorf("show --linked-from: %w", err)
				}
				all, err := state.backend.List()
				if err != nil {
					return fmt.Errorf("show --linked-from: list: %w", err)
				}
				ge := buildGovernanceEngine(all)
				for i, lnk := range src.Links {
					n, err := state.backend.Read(lnk.TargetID)
					if err != nil {
						continue // skip broken links silently
					}
					if i > 0 {
						fmt.Fprintln(w, "---")
					}
					protos := governedBy(ge, n.ID)
					if len(protos) > 0 {
						fmt.Fprintf(w, "governing protocols:\n")
						for _, p := range protos {
							fmt.Fprintf(w, "  - [%s] %s\n", p.ID, p.Title)
						}
						fmt.Fprintln(w)
					}
					data, err := n.Marshal()
					if err != nil {
						return fmt.Errorf("show: marshal: %w", err)
					}
					fmt.Fprint(w, string(data))
				}
				return nil
			}

			if len(args) == 0 {
				return fmt.Errorf("show: provide at least one ID or use --linked-from")
			}

			all, err := state.backend.List()
			if err != nil {
				return fmt.Errorf("show: list: %w", err)
			}
			ge := buildGovernanceEngine(all)

			for i, query := range args {
				if i > 0 {
					fmt.Fprintln(w, "---")
				}
				if vp := findVirtualProtocol(query); vp != nil {
					fmt.Fprintf(w, "---\nid: %s\ntitle: %s\napplies_when: %s\ntype: protocol\nstatus: permanent\n---\n\n%s", vp.ID, vp.Title, vp.AppliesWhen, vp.Body)
					continue
				}
				n, err := resolveNote(state, query)
				if err != nil {
					return fmt.Errorf("show: %w", err)
				}
				appendAccessLog(resolveCfgDir(), n.ID)
				protos := governedBy(ge, n.ID)

				if jsonOut {
					type protoRef struct {
						ID    string `json:"id"`
						Title string `json:"title"`
					}
					type showJSON struct {
						ID                 string     `json:"id"`
						Title              string     `json:"title"`
						Type               string     `json:"type"`
						Status             string     `json:"status"`
						Tags               []string   `json:"tags"`
						Created            string     `json:"created"`
						Modified           string     `json:"modified"`
						Body               string     `json:"body"`
						GoverningProtocols []protoRef `json:"governing_protocols"`
					}
					refs := make([]protoRef, len(protos))
					for j, p := range protos {
						refs[j] = protoRef{ID: p.ID, Title: p.Title}
					}
					if refs == nil {
						refs = []protoRef{}
					}
					out := showJSON{
						ID:                 n.ID,
						Title:              n.Title,
						Type:               string(n.Type),
						Status:             string(n.Status),
						Tags:               n.Tags,
						Created:            n.Created.UTC().Format(time.RFC3339Nano),
						Modified:           n.Modified.UTC().Format(time.RFC3339Nano),
						Body:               n.Body,
						GoverningProtocols: refs,
					}
					if out.Tags == nil {
						out.Tags = []string{}
					}
					enc := json.NewEncoder(w)
					enc.SetIndent("", "  ")
					if err := enc.Encode(out); err != nil {
						return fmt.Errorf("show: json: %w", err)
					}
					continue
				}

				if len(protos) > 0 {
					fmt.Fprintf(w, "governing protocols:\n")
					for _, p := range protos {
						fmt.Fprintf(w, "  - [%s] %s\n", p.ID, p.Title)
					}
					fmt.Fprintln(w)
				}
				byID := make(map[string]*note.Note, len(all))
				for _, a := range all {
					byID[a.ID] = a
				}
				data, err := n.Marshal()
				if err != nil {
					return fmt.Errorf("show: marshal: %w", err)
				}
				backlinkers := findBacklinkers(n.ID, all)
				rendered := renderWithResolvedLinks(string(data), n, byID, backlinkers, showRules)
				rendered = injectFreshness(rendered, n.Modified)
				fmt.Fprint(w, rendered)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&linkedFrom, "linked-from", "", "Show all notes linked from this ID")
	cmd.Flags().BoolVar(&jsonOut, "json", false, "Output note as JSON with governing_protocols")
	cmd.Flags().IntVar(&depth, "depth", 0, "Traverse outgoing links to this depth and print all reachable notes")
	cmd.Flags().BoolVar(&global, "global", false, "Show all global protocol notes (type:protocol with no outgoing governs links)")
	cmd.Flags().BoolVar(&showRules, "rules", false, "Append a ## Rule violations section (runs the rules engine over the notebook; omitted by default for speed)")
	return cmd
}

// loadSessionReads parses access.log and returns the set of note IDs read after the most recent
// "--global" sentinel for the current process's parent PID. Returns an empty map on any error.
func loadSessionReads(cfgDir string) map[string]bool {
	data, err := os.ReadFile(filepath.Join(cfgDir, "access.log"))
	if err != nil {
		return map[string]bool{}
	}
	ppid := strconv.Itoa(os.Getppid())
	var sessionStart int = -1
	lines := strings.Split(strings.TrimRight(string(data), "\n"), "\n")
	for i, line := range lines {
		parts := strings.Fields(line)
		// format: <RFC3339> <PPID> show <id>
		if len(parts) == 4 && parts[1] == ppid && parts[3] == "--global" {
			sessionStart = i
		}
	}
	result := map[string]bool{}
	if sessionStart < 0 {
		return result
	}
	for _, line := range lines[sessionStart+1:] {
		parts := strings.Fields(line)
		if len(parts) == 4 && parts[1] == ppid && parts[2] == "show" {
			result[parts[3]] = true
		}
	}
	return result
}

// resolveCfgDir returns the nn config directory from NN_CONFIG_DIR, XDG_CONFIG_HOME, or ~/.config/nn.
func resolveCfgDir() string {
	if d := os.Getenv("NN_CONFIG_DIR"); d != "" {
		return d
	}
	xdg := os.Getenv("XDG_CONFIG_HOME")
	if xdg == "" {
		home, _ := os.UserHomeDir()
		xdg = filepath.Join(home, ".config")
	}
	return filepath.Join(xdg, "nn")
}

// appendAccessLog records a note retrieval to the advisory access log.
// Failures are silently ignored — the log is advisory only.
// Each entry records the current process's parent PID so concurrent shell sessions
// can be distinguished when deriving session read-state.
func appendAccessLog(cfgDir, id string) {
	_ = os.MkdirAll(cfgDir, 0o755)
	logPath := filepath.Join(cfgDir, "access.log")

	// Prune entries older than 7 days, but only when file exceeds 50KB and last prune was >1h ago.
	cutoff := time.Now().UTC().Add(-7 * 24 * time.Hour)
	markerPath := logPath + ".pruned"
	if info, statErr := os.Stat(logPath); statErr == nil && info.Size() > 50*1024 {
		recentlyPruned := false
		if markerData, merr := os.ReadFile(markerPath); merr == nil {
			if t, perr := time.Parse(time.RFC3339, strings.TrimSpace(string(markerData))); perr == nil {
				if time.Since(t) < 24*time.Hour {
					recentlyPruned = true
				}
			}
		}
		if !recentlyPruned {
			if data, err := os.ReadFile(logPath); err == nil {
				var kept []string
				for _, line := range strings.Split(strings.TrimRight(string(data), "\n"), "\n") {
					if line == "" {
						continue
					}
					parts := strings.Fields(line)
					if len(parts) >= 1 {
						if t, err := time.Parse(time.RFC3339, parts[0]); err == nil && t.Before(cutoff) {
							continue
						}
					}
					kept = append(kept, line)
				}
				_ = os.WriteFile(logPath, []byte(strings.Join(kept, "\n")+"\n"), 0o644)
				_ = os.WriteFile(markerPath, []byte(time.Now().UTC().Format(time.RFC3339)), 0o644)
			}
		}
	}

	f, err := os.OpenFile(logPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()
	fmt.Fprintf(f, "%s %d show %s\n", time.Now().UTC().Format(time.RFC3339), os.Getppid(), id)
}

// governingProtocolsFromEngine returns the protocol notes that govern targetID,
// derived from the engine's governs_note predicate (direct + whole-tree
// representation + refines/extends specialization). This is the single source of
// truth for governance, replacing the ad-hoc findGoverningProtocols traversal.
// governanceEngine bundles a saturated rules engine with the note lookup its
// governs_note facts resolve against. Build it once per command with
// buildGovernanceEngine, then query per note with governedBy — the datalog
// fixpoint (which for representation subgraphs runs a transitive closure over
// all facts) must not be re-evaluated per shown note.
type governanceEngine struct {
	engine *rules.Engine
	byID   map[string]*note.Note
}

// buildGovernanceEngine loads facts + builtin rules and evaluates the fixpoint
// once. Returns nil on parse/eval failure (callers treat nil as "no governance
// derivable", matching the prior per-call error behavior).
func buildGovernanceEngine(all []*note.Note) *governanceEngine {
	byID := make(map[string]*note.Note, len(all))
	for _, n := range all {
		byID[n.ID] = n
	}
	e := rules.NewEngine()
	for _, f := range rules.FactsFromNotes(all) {
		e.AddFact(f)
	}
	builtin, err := rules.ParseProgram(rules.BuiltinRules())
	if err != nil {
		return nil
	}
	e.AddRules(builtin)
	if err := e.EvalFor("governs_note"); err != nil {
		return nil
	}
	return &governanceEngine{engine: e, byID: byID}
}

// governingProtocolsFromEngine builds a governance engine and queries it for a
// single note. Prefer buildGovernanceEngine + governedBy when resolving several
// notes so the fixpoint is evaluated once; this one-shot form remains for
// callers (and tests) that resolve a single note against a bespoke note set.
func governingProtocolsFromEngine(targetID string, all []*note.Note) []*note.Note {
	return governedBy(buildGovernanceEngine(all), targetID)
}

// governedBy returns the protocol notes that govern targetID, querying the
// already-saturated engine (no re-evaluation). A nil ge yields no protocols.
func governedBy(ge *governanceEngine, targetID string) []*note.Note {
	if ge == nil {
		return nil
	}
	seen := make(map[string]bool)
	var result []*note.Note
	for _, f := range ge.engine.Query("governs_note") {
		if len(f.Args) >= 2 && f.Args[1] == targetID {
			pID := f.Args[0]
			if seen[pID] {
				continue
			}
			if p := ge.byID[pID]; p != nil {
				seen[pID] = true
				result = append(result, p)
			}
		}
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ID < result[j].ID })
	return result
}

// resolveNote finds a note by exact ID or case-insensitive title substring.
// The special query "daily" resolves to today's Daily: YYYY-MM-DD note, creating it if absent.
func resolveNote(state *rootState, query string) (*note.Note, error) {
	if strings.ToLower(query) == "daily" {
		return resolveDailyNote(state)
	}
	n, err := state.backend.Read(query)
	if err == nil {
		return n, nil
	}
	all, listErr := state.backend.List()
	if listErr != nil {
		return nil, fmt.Errorf("%w", err)
	}
	type match struct{ id, title string }
	var matches []match
	for _, candidate := range all {
		if strings.Contains(strings.ToLower(candidate.Title), strings.ToLower(query)) {
			matches = append(matches, match{candidate.ID, candidate.Title})
		}
	}
	switch len(matches) {
	case 0:
		return nil, fmt.Errorf("no note found matching %q", query)
	case 1:
		return state.backend.Read(matches[0].id)
	default:
		return nil, fmt.Errorf("ambiguous query %q — %d matches; use full ID", query, len(matches))
	}
}

// resolveDailyNote finds or creates today's Daily: YYYY-MM-DD note.
// Created notes are tagged "daily" and expire in 7 days.
func resolveDailyNote(state *rootState) (*note.Note, error) {
	today := nowFn().Format("2006-01-02")
	todayTitle := "Daily: " + today

	all, err := state.backend.List()
	if err != nil {
		return nil, fmt.Errorf("daily: list: %w", err)
	}
	for _, candidate := range all {
		if candidate.Title == todayTitle {
			return state.backend.Read(candidate.ID)
		}
	}

	yesterday := nowFn().AddDate(0, 0, -1).Format("2006-01-02")
	yesterdayTitle := "Daily: " + yesterday
	var body string
	for _, candidate := range all {
		if candidate.Title == yesterdayTitle {
			yn, readErr := state.backend.Read(candidate.ID)
			if readErr == nil && yn.Body != "" {
				body = "### Yesterday\n\n" + stripDoneSection(yn.Body)
			}
			break
		}
	}

	expires := time.Now().UTC().AddDate(0, 0, 7)
	now := time.Now().UTC()
	n := &note.Note{
		ID:       note.GenerateID(),
		Title:    todayTitle,
		Type:     note.TypeObservation,
		Status:   note.StatusDraft,
		Tags:     []string{"daily"},
		Expires:  &expires,
		Created:  now,
		Modified: now,
		Body:     body,
	}
	if err := state.backend.Write(n); err != nil {
		return nil, fmt.Errorf("daily: create: %w", err)
	}
	return n, nil
}

// stripCarryForwardSections removes sections that must not accumulate across days.
// It strips ## Done (completed work) and ### Yesterday (already-carried content)
// so each day's seed is clean.
func stripDoneSection(body string) string {
	lines := strings.Split(body, "\n")
	var out []string
	inStripped := false
	for _, line := range lines {
		if strings.HasPrefix(line, "## Done") || strings.HasPrefix(line, "### Yesterday") {
			inStripped = true
			continue
		}
		if inStripped {
			// A same-or-higher-level heading ends the stripped section.
			if strings.HasPrefix(line, "## ") || strings.HasPrefix(line, "### ") {
				inStripped = false
			} else {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n")
}

// findVirtualProtocol returns the virtualProtocol whose ID matches query exactly,
// or nil if no virtual protocol matches.
func findVirtualProtocol(query string) *virtualProtocol {
	for i, vp := range virtualGlobalProtocols {
		if vp.ID == query {
			return &virtualGlobalProtocols[i]
		}
	}
	return nil
}

// findBacklinkers returns all notes in all that link to targetID (any link type).
func findBacklinkers(targetID string, all []*note.Note) []*note.Note {
	var result []*note.Note
	for _, n := range all {
		for _, lnk := range n.Links {
			if lnk.TargetID == targetID {
				result = append(result, n)
				break
			}
		}
	}
	return result
}

// injectFreshness inserts a "freshness: <tier>" line after the closing "---" of the
// YAML frontmatter in a marshaled note string.
func injectFreshness(raw string, modified time.Time) string {
	const sep = "---\n"
	// Find the second "---\n" which closes the frontmatter.
	first := strings.Index(raw, sep)
	if first < 0 {
		return raw
	}
	second := strings.Index(raw[first+len(sep):], sep)
	if second < 0 {
		return raw
	}
	insertAt := first + len(sep) + second + len(sep)
	label := freshnessLabel(modified)
	return raw[:insertAt] + "freshness: " + label + "\n" + raw[insertAt:]
}

// freshnessLabel returns a full staleness description including tier, human-readable age, and action hint.
// Tiers: fresh (< 3 days), aging (3–14 days), stale (> 14 days).
func freshnessLabel(modified time.Time) string {
	age := time.Since(modified)
	ageStr := humanAge(age)
	switch {
	case age < 3*24*time.Hour:
		return "fresh (" + ageStr + " — likely current)"
	case age < 14*24*time.Hour:
		return "aging (" + ageStr + " — may need recheck)"
	default:
		return "stale (" + ageStr + " — content may be outdated, verify before use)"
	}
}

// humanAge formats a duration as a short human-readable age string like "2 days ago" or "5 hours ago".
func humanAge(d time.Duration) string {
	switch {
	case d < time.Hour:
		m := int(d.Minutes())
		if m <= 1 {
			return "1 minute ago"
		}
		return fmt.Sprintf("%d minutes ago", m)
	case d < 24*time.Hour:
		h := int(d.Hours())
		if h == 1 {
			return "1 hour ago"
		}
		return fmt.Sprintf("%d hours ago", h)
	default:
		days := int(d.Hours() / 24)
		if days == 1 {
			return "1 day ago"
		}
		return fmt.Sprintf("%d days ago", days)
	}
}

// renderWithResolvedLinks replaces the raw ## Links section in marshaled note output
// with title-resolved link lines, and appends a ## Backlinks section.
// Target IDs are resolved via byID; unresolved IDs fall back to the bare ID.
func renderWithResolvedLinks(raw string, n *note.Note, byID map[string]*note.Note, backlinkers []*note.Note, showRules bool) string {
	var buf strings.Builder
	if len(n.Links) > 0 {
		const linkSection = "\n## Links\n\n"
		cut := strings.Index(raw, linkSection)
		if cut >= 0 {
			buf.WriteString(raw[:cut])
			buf.WriteString(linkSection)
			for _, lnk := range n.Links {
				title := lnk.TargetID
				if t, ok := byID[lnk.TargetID]; ok {
					title = t.Title
				}
				switch {
				case lnk.Type != "" && lnk.Status != "":
					fmt.Fprintf(&buf, "- [[%s|%s]] [%s] {%s} — %s\n", lnk.TargetID, title, lnk.Type, lnk.Status, lnk.Annotation)
				case lnk.Type != "":
					fmt.Fprintf(&buf, "- [[%s|%s]] [%s] — %s\n", lnk.TargetID, title, lnk.Type, lnk.Annotation)
				case lnk.Status != "":
					fmt.Fprintf(&buf, "- [[%s|%s]] {%s} — %s\n", lnk.TargetID, title, lnk.Status, lnk.Annotation)
				default:
					fmt.Fprintf(&buf, "- [[%s|%s]] — %s\n", lnk.TargetID, title, lnk.Annotation)
				}
			}
		} else {
			buf.WriteString(raw)
		}
	} else {
		buf.WriteString(raw)
	}
	if len(backlinkers) > 0 {
		fmt.Fprintf(&buf, "\n## Backlinks (%d)\n\n", len(backlinkers))
		for _, b := range backlinkers {
			for _, lnk := range b.Links {
				if lnk.TargetID == n.ID {
					switch {
					case lnk.Type != "" && lnk.Status != "":
						fmt.Fprintf(&buf, "- [[%s|%s]] [%s] {%s} — %s\n", b.ID, b.Title, lnk.Type, lnk.Status, lnk.Annotation)
					case lnk.Type != "":
						fmt.Fprintf(&buf, "- [[%s|%s]] [%s] — %s\n", b.ID, b.Title, lnk.Type, lnk.Annotation)
					case lnk.Status != "":
						fmt.Fprintf(&buf, "- [[%s|%s]] {%s} — %s\n", b.ID, b.Title, lnk.Status, lnk.Annotation)
					default:
						fmt.Fprintf(&buf, "- [[%s|%s]] — %s\n", b.ID, b.Title, lnk.Annotation)
					}
					break
				}
			}
		}
	}
	// The rule-violations section runs the full rules engine over the notebook,
	// so it is opt-in (--rules) to keep default nn show fast.
	if showRules {
		buf.WriteString(ruleViolationsSection(n, byID))
	}
	return buf.String()
}

// ruleViolationsSection evaluates the notebook's rules (built-in + nn-rule
// fences) and returns a "## Rule violations" section listing only the
// violations whose subject is note n. This closes the protocol-enforcement
// loop: a type:protocol note's nn-rule flags the notes it governs, and that is
// surfaced when those notes are shown. Returns "" when n has no violations.
func ruleViolationsSection(n *note.Note, byID map[string]*note.Note) string {
	all := make([]*note.Note, 0, len(byID))
	for _, m := range byID {
		all = append(all, m)
	}

	e := rules.NewEngine()
	for _, f := range rules.FactsFromNotes(all) {
		e.AddFact(f)
	}
	builtin, err := rules.ParseProgram(rules.BuiltinRules())
	if err != nil {
		return ""
	}
	e.AddRules(builtin)
	for _, m := range all {
		userRules, _ := rules.ExtractFenceRules(m.ID, m.Body)
		e.AddRules(userRules)
	}
	if err := e.Eval(); err != nil {
		// A non-stratifiable user ruleset must not break show output.
		return ""
	}

	var reasons []string
	for _, f := range e.Query("violation") {
		if len(f.Args) >= 2 && f.Args[0] == n.ID {
			reasons = append(reasons, f.Args[1])
		}
	}
	if len(reasons) == 0 {
		return ""
	}
	sort.Strings(reasons)

	var b strings.Builder
	fmt.Fprintf(&b, "\n## Rule violations (%d)\n\n", len(reasons))
	for _, r := range reasons {
		fmt.Fprintf(&b, "- %s\n", r)
	}
	return b.String()
}
