package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/jaresty/nn/internal/note"
)

// nowFn is the time source for daily note date labels. Tests override it to simulate timezone offsets.
var nowFn = time.Now

// virtualProtocol is a hardcoded protocol always included in nn show --global output.
// Body contains the full constraint text; AppliesWhen is a one-line application rule
// shown in compact --global output so the LLM can decide whether to fetch the full body.
type virtualProtocol struct {
	ID          string
	Title       string
	AppliesWhen string
	Body        string
}

// virtualGlobalProtocols are hardcoded protocols always included in nn show --global output.
// Add entries here to register additional tool-level meta-protocols.
var virtualGlobalProtocols = []virtualProtocol{
	{
		ID:          "virtual-nn-capture-discipline",
		Title:       "Protocol: nn-capture-discipline",
		AppliesWhen: "before any Read tool call or file-reading Bash tool call",
		Body: "Before any Read tool call or file-reading Bash tool call not on the allow-list, the last " +
			"line of your assistant text before that call must begin with `Gate:` followed by either:\n" +
			"- `Gate: allow-listed — [item]` for allow-listed actions\n" +
			"- `Gate: Search rationale: [topic] — [action]` otherwise\n\n" +
			"Then run `nn list --search \"<topic>\" --json` as the complete Bash tool call text — " +
			"no additional flags, arguments, or shell operators. " +
			"The full JSON array must land in the transcript as a tool result. " +
			"The assistant text immediately following that result must quote a verbatim " +
			"title from the JSON array, or write `zero results` if the array is empty. If any quoted " +
			"title shares a word with [topic], run `nn show <id>` (id = first matching result's `id` " +
			"field) before the gated action. `nn show` calls within the search window do not reset it.\n\n" +
			"**Allow-list (no gate required):**\n" +
			"- Any file written or generated by this session (Write, Edit, or session command output)\n" +
			"- Any command producing output solely from session state (tests, builds, linters)\n" +
			"- Live machine-generated output (JSON, log, status) where a resource identifier for that " +
			"system appears in the conversation above this action\n\n" +
			"After the gated action, quote a verbatim excerpt from the result. Then either capture " +
			"with `nn new` / `nn update` / `nn link`, or skip with the excerpt, the source, and " +
			"`result is a runtime value` if the result is execution output with no reuse across sessions.\n",
	},
	{
		ID:          "virtual-nn-cli-reference",
		Title:       "Protocol: nn CLI reference",
		AppliesWhen: "always — reference for valid nn command flags, types, and statuses",
		Body: "**nn new** `--title \"...\" --type <type> --content \"...\" --no-edit [--tags \"t1,t2\"] [--link-to <id> --annotation \"...\"] [--applies-when \"...\"] [--expires YYYY-MM-DD] [--expires-when \"condition\"]`\n" +
			"Valid --type: concept|argument|model|hypothesis|observation|question|protocol\n" +
			"New notes are always created as draft. Promote with: `nn update <id> --status reviewed`\n\n" +
			"**nn update** `<id> --since <RFC3339> --status <status>` | `--title \"...\"` | `--applies-when \"...\"` | `--expires YYYY-MM-DD` | `--expires-when \"condition\"` | `--content \"...\" --no-edit`\n" +
			"Valid --status: draft|reviewed|permanent\n" +
			"--since is required: read 'modified:' from nn show output; update is rejected if the note was changed after that timestamp\n\n" +
			"**nn remind** `\"content\" [--for N] [--expires YYYY-MM-DD]` — creates observation tagged 'reminder', permanent, expires today+1d by default; surfaces in nn show --global\n\n" +
			"**nn list** `--search \"<q>\" --show-first --json [--fields id,title,...]` | `--type <type>` | `--status <status>` | `--orphan` | `--since <ISO>` | `--expired` | `--has-expires`\n" +
			"Valid --fields: id|title|type|status|tags|applies_when|excerpt|score|modified|match_reason|is_protocol|link_count|backlink_count|created|body_preview (requires --json; errors on unknown field)\n\n" +
			"**nn show** `<id>` | `--global`\n" +
			"`nn show` output must not be piped to `head`, `tail`, `less`, or `more`. Pipe the full output or omit the pipe — the complete note body is required for accurate retrieval.\n\n" +
			"**nn link** `<from> <to> --type <type> --annotation \"...\"`\n" +
			"Valid --type: refines|contradicts|source-of|extends|supports|questions|governs\n\n" +
			"**nn show** `<id> --depth N` — traverse N hops of outgoing links from a note\n\n" +
			"**nn path** `<id-a> <id-b>` — shortest path between two notes\n\n" +
			"**nn clusters** — topological clusters via label propagation\n\n" +
			"**nn list** `--similar <id>` — BM25 similarity (notes sharing vocabulary but not linked)\n\n" +
			"**nn graph** `[--json]` — export full graph as JSON `{ \"nodes\": [...], \"edges\": [...] }`\n\n" +
			"**nn graph show** `--focus <id> [--depth N]` — subgraph centered on a note (LLM-facing; default depth 2)\n\n" +
			"For the full command reference, invoke `/nn-guide`.\n",
	},
	{
		ID:          "virtual-nn-error-handling",
		Title:       "Protocol: search nn before workarounding an unexpected command failure",
		AppliesWhen: "when a Bash command, CLI tool, or test fails",
		Body: "When a command fails, run `nn list --search \"<topic>\" --json` before attempting a workaround or fix. " +
			"Prior sessions may have captured the root cause, a known workaround, or a relevant constraint. " +
			"Acting without searching risks repeating a diagnosed problem.\n\n" +
			"**Skip condition A — pre-declared:** if the immediately preceding assistant turn contains a line beginning " +
			"`Expected FAIL: <reason>` (case-insensitive), the lookup is not required. " +
			"Write: `Skipping lookup: cited \"Expected FAIL: <reason>\"` quoting the declaration verbatim.\n\n" +
			"**Skip condition B — self-evident:** if the error output contains a substring that names the cause without ambiguity " +
			"— such as \"No such file\", \"command not found\", \"unrecognized token\", or \"exit status 1\" from a grep/find/cat invocation — " +
			"the lookup is not required. " +
			"Write: `Skipping lookup: self-evident — \"<quoted error substring>\"` quoting the exact substring from the tool output verbatim. " +
			"Absence of either skip declaration means the lookup is required.\n",
	},
}

// protocolDerivationBlock is appended to every protocol note in plain-text display.
// It instructs any LLM reading the note to derive how the protocol applies before responding.
const protocolDerivationBlock = `
<!-- nn:display-only — the following block is injected by nn show and is NOT part of the note body. Do not include it in nn update --content or any note edit. -->

## Protocols

For each protocol listed above:
1. Evaluate its applies_when condition against the current request.
2. If it holds: run ` + "`nn show <id>`" + ` to load the full body, then treat it as a binding constraint.
3. If a protocol has no applies_when field: add an applies_when value via ` + "`nn update <id> --field applies_when --value \"...\"`" + ` before proceeding.

Before responding to any message this session, output a ` + "`## Protocols`" + ` block.
For each active protocol, write one sentence stating how it applies to this specific
request — or "not applicable" if it doesn't. Place this block before your substantive
response.
`

func newShowCmd(state *rootState) *cobra.Command {
	var linkedFrom string
	var jsonOut bool
	var depth int
	var global bool

	cmd := &cobra.Command{
		Use:   "show <id-or-title> [<id-or-title>...]",
		Short: "Print note content to stdout (accepts ID or title substring; --depth N for graph traversal)",
		Args:  cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			w := outWriter(cmd)

			if global {
				all, err := state.backend.List()
				if err != nil {
					return fmt.Errorf("show --global: %w", err)
				}
				first := true
				for _, vp := range virtualGlobalProtocols {
					if !first {
						fmt.Fprintln(w, "---")
					}
					first = false
					fmt.Fprintf(w, "id: %s\ntitle: %s\ntype: protocol\nstatus: permanent\napplies_when: %s\n---\n\n%s", vp.ID, vp.Title, vp.AppliesWhen, vp.Body)
				}
				for _, n := range all {
					if n.Type != note.TypeProtocol {
						continue
					}
					hasGoverns := false
					for _, lnk := range n.Links {
						if lnk.Type == "governs" {
							hasGoverns = true
							break
						}
					}
					if hasGoverns {
						continue
					}
					if !first {
						fmt.Fprintln(w, "---")
					}
					first = false
					fmt.Fprintf(w, "id: %s\ntitle: %s\n", n.ID, n.Title)
					if n.AppliesWhen != "" {
						fmt.Fprintf(w, "applies_when: %s\n", n.AppliesWhen)
					}
				}
				now := time.Now().UTC()
				var activeReminders []*note.Note
				for _, n := range all {
					hasReminder := false
					for _, tag := range n.Tags {
						if tag == "reminder" {
							hasReminder = true
							break
						}
					}
					if hasReminder && (n.Expires == nil || !n.Expires.Before(now)) {
						activeReminders = append(activeReminders, n)
					}
				}
				if len(activeReminders) > 0 {
					fmt.Fprintln(w, "---")
					fmt.Fprintln(w, "## Reminders")
					fmt.Fprintln(w)
					for _, n := range activeReminders {
						fmt.Fprintf(w, "### %s\n\n", n.Title)
						if n.Expires != nil {
							fmt.Fprintf(w, "expires: %s\n", n.Expires.Format("2006-01-02"))
						}
						if n.ExpiresWhen != "" {
							fmt.Fprintf(w, "expires_when: %s\n", n.ExpiresWhen)
						}
						fmt.Fprintf(w, "\n%s\n\n", n.Body)
					}
				}
				if dn, dnErr := resolveDailyNote(state); dnErr == nil {
					fmt.Fprintln(w, "---")
					byID := make(map[string]*note.Note, len(all))
					for _, a := range all {
						byID[a.ID] = a
					}
					backlinkers := findBacklinkers(dn.ID, all)
					if data, merr := dn.Marshal(); merr == nil {
						rendered := renderWithResolvedLinks(string(data), dn, byID, backlinkers)
						fmt.Fprint(w, rendered)
					} else {
						fmt.Fprintf(w, "id: %s\ntitle: %s\ntype: observation\nstatus: %s\ntags: daily\n---\n\n%s\n", dn.ID, dn.Title, dn.Status, dn.Body)
					}
				}

				fmt.Fprint(w, protocolDerivationBlock)
				return nil
			}

			if depth > 0 {
				if len(args) != 1 {
					return fmt.Errorf("show --depth: provide exactly one ID")
				}
				root, err := resolveNote(state, args[0])
				if err != nil {
					return fmt.Errorf("show --depth: %w", err)
				}
				all, err := state.backend.List()
				if err != nil {
					return fmt.Errorf("show --depth: list: %w", err)
				}
				byID := make(map[string]*note.Note, len(all))
				for _, n := range all {
					byID[n.ID] = n
				}
				entries := bfsDepth(root, byID, depth)
				if jsonOut {
					return printDepthJSON(w, entries)
				}
				return printDepthMarkdown(w, entries)
			}

			if linkedFrom != "" {
				src, err := resolveNote(state, linkedFrom)
				if err != nil {
					return fmt.Errorf("show --linked-from: %w", err)
				}
				all, err := state.backend.List()
				if err != nil {
					return fmt.Errorf("show --linked-from: list: %w", err)
				}
				for i, lnk := range src.Links {
					n, err := state.backend.Read(lnk.TargetID)
					if err != nil {
						continue // skip broken links silently
					}
					if i > 0 {
						fmt.Fprintln(w, "---")
					}
					protos := findGoverningProtocols(n.ID, all)
					if len(protos) > 0 {
						fmt.Fprintf(w, "governing protocols:\n")
						for _, p := range protos {
							fmt.Fprintf(w, "  - [%s] %s\n", p.ID, p.Title)
						}
						fmt.Fprintln(w)
					}
					data, err := n.Marshal()
					if err != nil {
						return fmt.Errorf("show: marshal: %w", err)
					}
					fmt.Fprint(w, string(data))
				}
				return nil
			}

			if len(args) == 0 {
				return fmt.Errorf("show: provide at least one ID or use --linked-from")
			}

			all, err := state.backend.List()
			if err != nil {
				return fmt.Errorf("show: list: %w", err)
			}

			for i, query := range args {
				if i > 0 {
					fmt.Fprintln(w, "---")
				}
				if vp := findVirtualProtocol(query); vp != nil {
					fmt.Fprintf(w, "---\nid: %s\ntitle: %s\napplies_when: %s\ntype: protocol\nstatus: permanent\n---\n\n%s", vp.ID, vp.Title, vp.AppliesWhen, vp.Body)
					continue
				}
				n, err := resolveNote(state, query)
				if err != nil {
					return fmt.Errorf("show: %w", err)
				}
				appendAccessLog(n.ID)
				protos := findGoverningProtocols(n.ID, all)

				if jsonOut {
					type protoRef struct {
						ID    string `json:"id"`
						Title string `json:"title"`
					}
					type showJSON struct {
						ID                  string     `json:"id"`
						Title               string     `json:"title"`
						Type                string     `json:"type"`
						Status              string     `json:"status"`
						Tags                []string   `json:"tags"`
						Created             string     `json:"created"`
						Modified            string     `json:"modified"`
						Body                string     `json:"body"`
						GoverningProtocols  []protoRef `json:"governing_protocols"`
					}
					refs := make([]protoRef, len(protos))
					for j, p := range protos {
						refs[j] = protoRef{ID: p.ID, Title: p.Title}
					}
					if refs == nil {
						refs = []protoRef{}
					}
					out := showJSON{
						ID:                 n.ID,
						Title:              n.Title,
						Type:               string(n.Type),
						Status:             string(n.Status),
						Tags:               n.Tags,
						Created:            n.Created.UTC().Format("2006-01-02T15:04:05Z"),
						Modified:           n.Modified.UTC().Format("2006-01-02T15:04:05Z"),
						Body:               n.Body,
						GoverningProtocols: refs,
					}
					if out.Tags == nil {
						out.Tags = []string{}
					}
					enc := json.NewEncoder(w)
					enc.SetIndent("", "  ")
					if err := enc.Encode(out); err != nil {
						return fmt.Errorf("show: json: %w", err)
					}
					continue
				}

				if len(protos) > 0 {
					fmt.Fprintf(w, "governing protocols:\n")
					for _, p := range protos {
						fmt.Fprintf(w, "  - [%s] %s\n", p.ID, p.Title)
					}
					fmt.Fprintln(w)
				}
				byID := make(map[string]*note.Note, len(all))
				for _, a := range all {
					byID[a.ID] = a
				}
				data, err := n.Marshal()
				if err != nil {
					return fmt.Errorf("show: marshal: %w", err)
				}
				backlinkers := findBacklinkers(n.ID, all)
				rendered := renderWithResolvedLinks(string(data), n, byID, backlinkers)
				rendered = injectFreshness(rendered, n.Modified)
				fmt.Fprint(w, rendered)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&linkedFrom, "linked-from", "", "Show all notes linked from this ID")
	cmd.Flags().BoolVar(&jsonOut, "json", false, "Output note as JSON with governing_protocols")
	cmd.Flags().IntVar(&depth, "depth", 0, "Traverse outgoing links to this depth and print all reachable notes")
	cmd.Flags().BoolVar(&global, "global", false, "Show all global protocol notes (type:protocol with no outgoing governs links)")
	return cmd
}

// appendAccessLog records a note retrieval to the advisory access log.
// Failures are silently ignored — the log is advisory only.
func appendAccessLog(id string) {
	cfgDir := os.Getenv("NN_CONFIG_DIR")
	if cfgDir == "" {
		xdg := os.Getenv("XDG_CONFIG_HOME")
		if xdg == "" {
			home, _ := os.UserHomeDir()
			xdg = filepath.Join(home, ".config")
		}
		cfgDir = filepath.Join(xdg, "nn")
	}
	_ = os.MkdirAll(cfgDir, 0o755)
	f, err := os.OpenFile(filepath.Join(cfgDir, "access.log"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()
	fmt.Fprintf(f, "%s show %s\n", time.Now().UTC().Format(time.RFC3339), id)
}

// findGoverningProtocols returns all notes that link to targetID with type "governs".
func findGoverningProtocols(targetID string, all []*note.Note) []*note.Note {
	var result []*note.Note
	for _, n := range all {
		for _, lnk := range n.Links {
			if lnk.TargetID == targetID && lnk.Type == "governs" {
				result = append(result, n)
				break
			}
		}
	}
	return result
}

// resolveNote finds a note by exact ID or case-insensitive title substring.
// The special query "daily" resolves to today's Daily: YYYY-MM-DD note, creating it if absent.
func resolveNote(state *rootState, query string) (*note.Note, error) {
	if strings.ToLower(query) == "daily" {
		return resolveDailyNote(state)
	}
	n, err := state.backend.Read(query)
	if err == nil {
		return n, nil
	}
	all, listErr := state.backend.List()
	if listErr != nil {
		return nil, fmt.Errorf("%w", err)
	}
	type match struct{ id, title string }
	var matches []match
	for _, candidate := range all {
		if strings.Contains(strings.ToLower(candidate.Title), strings.ToLower(query)) {
			matches = append(matches, match{candidate.ID, candidate.Title})
		}
	}
	switch len(matches) {
	case 0:
		return nil, fmt.Errorf("no note found matching %q", query)
	case 1:
		return state.backend.Read(matches[0].id)
	default:
		return nil, fmt.Errorf("ambiguous query %q — %d matches; use full ID", query, len(matches))
	}
}

// resolveDailyNote finds or creates today's Daily: YYYY-MM-DD note.
// Created notes are tagged "daily" and expire in 7 days.
func resolveDailyNote(state *rootState) (*note.Note, error) {
	today := nowFn().Format("2006-01-02")
	todayTitle := "Daily: " + today

	all, err := state.backend.List()
	if err != nil {
		return nil, fmt.Errorf("daily: list: %w", err)
	}
	for _, candidate := range all {
		if candidate.Title == todayTitle {
			return state.backend.Read(candidate.ID)
		}
	}

	yesterday := nowFn().AddDate(0, 0, -1).Format("2006-01-02")
	yesterdayTitle := "Daily: " + yesterday
	var body string
	for _, candidate := range all {
		if candidate.Title == yesterdayTitle {
			yn, readErr := state.backend.Read(candidate.ID)
			if readErr == nil && yn.Body != "" {
				body = "### Yesterday\n\n" + stripDoneSection(yn.Body)
			}
			break
		}
	}

	expires := time.Now().UTC().AddDate(0, 0, 7)
	now := time.Now().UTC()
	n := &note.Note{
		ID:       note.GenerateID(),
		Title:    todayTitle,
		Type:     note.TypeObservation,
		Status:   note.StatusDraft,
		Tags:     []string{"daily"},
		Expires:  &expires,
		Created:  now,
		Modified: now,
		Body:     body,
	}
	if err := state.backend.Write(n); err != nil {
		return nil, fmt.Errorf("daily: create: %w", err)
	}
	return n, nil
}

// stripDoneSection removes the ## Done section from a daily note body so it is
// not carried forward when yesterday's note seeds today's note.
func stripDoneSection(body string) string {
	lines := strings.Split(body, "\n")
	var out []string
	inDone := false
	for _, line := range lines {
		if strings.HasPrefix(line, "## Done") {
			inDone = true
			continue
		}
		if inDone && strings.HasPrefix(line, "## ") {
			inDone = false
		}
		if !inDone {
			out = append(out, line)
		}
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n")
}

// findVirtualProtocol returns the virtualProtocol whose ID matches query exactly,
// or nil if no virtual protocol matches.
func findVirtualProtocol(query string) *virtualProtocol {
	for i, vp := range virtualGlobalProtocols {
		if vp.ID == query {
			return &virtualGlobalProtocols[i]
		}
	}
	return nil
}

// findBacklinkers returns all notes in all that link to targetID (any link type).
func findBacklinkers(targetID string, all []*note.Note) []*note.Note {
	var result []*note.Note
	for _, n := range all {
		for _, lnk := range n.Links {
			if lnk.TargetID == targetID {
				result = append(result, n)
				break
			}
		}
	}
	return result
}

// injectFreshness inserts a "freshness: <tier>" line after the closing "---" of the
// YAML frontmatter in a marshaled note string.
func injectFreshness(raw string, modified time.Time) string {
	const sep = "---\n"
	// Find the second "---\n" which closes the frontmatter.
	first := strings.Index(raw, sep)
	if first < 0 {
		return raw
	}
	second := strings.Index(raw[first+len(sep):], sep)
	if second < 0 {
		return raw
	}
	insertAt := first + len(sep) + second + len(sep)
	label := freshnessLabel(modified)
	return raw[:insertAt] + "freshness: " + label + "\n" + raw[insertAt:]
}

// freshnessLabel returns a full staleness description including tier, human-readable age, and action hint.
// Tiers: fresh (< 3 days), aging (3–14 days), stale (> 14 days).
func freshnessLabel(modified time.Time) string {
	age := time.Since(modified)
	ageStr := humanAge(age)
	switch {
	case age < 3*24*time.Hour:
		return "fresh (" + ageStr + " — likely current)"
	case age < 14*24*time.Hour:
		return "aging (" + ageStr + " — may need recheck)"
	default:
		return "stale (" + ageStr + " — content may be outdated, verify before use)"
	}
}

// humanAge formats a duration as a short human-readable age string like "2 days ago" or "5 hours ago".
func humanAge(d time.Duration) string {
	switch {
	case d < time.Hour:
		m := int(d.Minutes())
		if m <= 1 {
			return "1 minute ago"
		}
		return fmt.Sprintf("%d minutes ago", m)
	case d < 24*time.Hour:
		h := int(d.Hours())
		if h == 1 {
			return "1 hour ago"
		}
		return fmt.Sprintf("%d hours ago", h)
	default:
		days := int(d.Hours() / 24)
		if days == 1 {
			return "1 day ago"
		}
		return fmt.Sprintf("%d days ago", days)
	}
}

// renderWithResolvedLinks replaces the raw ## Links section in marshaled note output
// with title-resolved link lines, and appends a ## Backlinks section.
// Target IDs are resolved via byID; unresolved IDs fall back to the bare ID.
func renderWithResolvedLinks(raw string, n *note.Note, byID map[string]*note.Note, backlinkers []*note.Note) string {
	var buf strings.Builder
	if len(n.Links) > 0 {
		const linkSection = "\n## Links\n\n"
		cut := strings.Index(raw, linkSection)
		if cut >= 0 {
			buf.WriteString(raw[:cut])
			buf.WriteString(linkSection)
			for _, lnk := range n.Links {
				title := lnk.TargetID
				if t, ok := byID[lnk.TargetID]; ok {
					title = t.Title
				}
				switch {
				case lnk.Type != "" && lnk.Status != "":
					fmt.Fprintf(&buf, "- [[%s|%s]] [%s] {%s} — %s\n", lnk.TargetID, title, lnk.Type, lnk.Status, lnk.Annotation)
				case lnk.Type != "":
					fmt.Fprintf(&buf, "- [[%s|%s]] [%s] — %s\n", lnk.TargetID, title, lnk.Type, lnk.Annotation)
				case lnk.Status != "":
					fmt.Fprintf(&buf, "- [[%s|%s]] {%s} — %s\n", lnk.TargetID, title, lnk.Status, lnk.Annotation)
				default:
					fmt.Fprintf(&buf, "- [[%s|%s]] — %s\n", lnk.TargetID, title, lnk.Annotation)
				}
			}
		} else {
			buf.WriteString(raw)
		}
	} else {
		buf.WriteString(raw)
	}
	if len(backlinkers) > 0 {
		fmt.Fprintf(&buf, "\n## Backlinks (%d)\n\n", len(backlinkers))
		for _, b := range backlinkers {
			for _, lnk := range b.Links {
				if lnk.TargetID == n.ID {
					if lnk.Annotation != "" {
						fmt.Fprintf(&buf, "- [[%s|%s]] — %s\n", b.ID, b.Title, lnk.Annotation)
					} else {
						fmt.Fprintf(&buf, "- [[%s|%s]]\n", b.ID, b.Title)
					}
					break
				}
			}
		}
	}
	return buf.String()
}
