package cmd

import (
	"strings"
	"testing"
)

// Assertion: virtual capture discipline body uses explicit allow-list, not self-assessed trigger.
func TestVirtualCaptureDisciplineNoSelfAssessedTrigger(t *testing.T) {
	_, execute := setupNotebook(t)
	out, err := execute("show", "virtual-nn-capture-discipline")
	if err != nil {
		t.Fatalf("nn show --global: %v", err)
	}
	if strings.Contains(out, "introduces new information not already present in the conversation") {
		t.Errorf("virtual protocol should not contain self-assessed trigger phrase; got:\n%s", out)
	}
}

// Assertion: virtual capture discipline uses search window model (nn show calls permitted to intervene).
func TestVirtualCaptureDisciplineSearchWindow(t *testing.T) {
	_, execute := setupNotebook(t)
	out, err := execute("show", "virtual-nn-capture-discipline")
	if err != nil {
		t.Fatalf("nn show virtual-nn-capture-discipline: %v", err)
	}
	if strings.Contains(out, "result block occupies the position immediately before the gated tool call") {
		t.Errorf("body must not contain old adjacency-position language; got:\n%s", out)
	}
	if !strings.Contains(out, "search window do not reset it") {
		t.Errorf("expected search window model in body; got:\n%s", out)
	}
}

// Assertion D5: trigger is structural (Read tool call / file-reading Bash), not semantic session-provenance.
func TestVirtualCaptureDisciplineStructuralTrigger(t *testing.T) {
	_, execute := setupNotebook(t)
	out, err := execute("show", "virtual-nn-capture-discipline")
	if err != nil {
		t.Fatalf("nn show virtual-nn-capture-discipline: %v", err)
	}
	if !strings.Contains(out, "Read tool call or file-reading Bash tool call") {
		t.Errorf("expected structural trigger in body; got:\n%s", out)
	}
	if strings.Contains(out, "not authored this session") {
		t.Errorf("body must not contain semantic session-provenance trigger; got:\n%s", out)
	}
}

// Assertion D6: body requires explicit Gate: line before every gated tool call.
func TestVirtualCaptureDisciplineGateLine(t *testing.T) {
	_, execute := setupNotebook(t)
	out, err := execute("show", "virtual-nn-capture-discipline")
	if err != nil {
		t.Fatalf("nn show virtual-nn-capture-discipline: %v", err)
	}
	if !strings.Contains(out, "Gate: allow-listed") {
		t.Errorf("expected 'Gate: allow-listed' form in body; got:\n%s", out)
	}
	if !strings.Contains(out, "Gate: Search rationale:") {
		t.Errorf("expected 'Gate: Search rationale:' form in body; got:\n%s", out)
	}
}

// Assertion D7: body requires Gate: line as last line before gated call, and uses session-written allow-list.
func TestVirtualCaptureDisciplineLastLineGate(t *testing.T) {
	_, execute := setupNotebook(t)
	out, err := execute("show", "virtual-nn-capture-discipline")
	if err != nil {
		t.Fatalf("nn show virtual-nn-capture-discipline: %v", err)
	}
	if !strings.Contains(out, "last line of your assistant text before that call must begin with") {
		t.Errorf("expected last-line Gate: requirement in body; got:\n%s", out)
	}
	if !strings.Contains(out, "Any file written or generated by this session") {
		t.Errorf("expected session-written allow-list clause in body; got:\n%s", out)
	}
}

// Assertion D8: body handles empty/truncated output via skip-search: prefix (no "zero results" wording).
func TestVirtualCaptureDisciplineZeroResults(t *testing.T) {
	_, execute := setupNotebook(t)
	out, err := execute("show", "virtual-nn-capture-discipline")
	if err != nil {
		t.Fatalf("nn show virtual-nn-capture-discipline: %v", err)
	}
	if strings.Contains(out, "rephrased") {
		t.Errorf("body must not require retry-with-rephrased; got:\n%s", out)
	}
	if !strings.Contains(out, "skip-search:") {
		t.Errorf("expected 'skip-search:' empty/truncated exit in body; got:\n%s", out)
	}
}
